MIN_CONTOUR_AREA = 200

# ROI ratio start point and end point
START_X = 0.5
START_Y = 0.6
END_X = 1
END_Y = 1

MAX_DISAPPEAR_FRAME_COUNTS = 2
MAX_OBJECT_DIST = 50  # pixels

CV_TRACKER_TYPES = ['BOOSTING', 'MIL', 'KCF', 'TLD', 'MOSSE']
